development:
  adapter: postgresql
  encoding: unicode
  database: ChessExplained_development
  pool: 5
  username: JackMallers
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ChessExplained_test
  pool: 5
  username: JackMallers
  password:
