development:
  adapter: postgresql
  encoding: unicode
  database: ChessExplained_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ChessExplained_test
  host: localhost
  pool: 5
